### ISSUE TITLE
HSM: Post Utility Error

### ISSUE THREAD

**Issue by dudleyjosh** [Autodesk/cam-posteditor#12]
When I follow the directions of how to use the HSM plugin and press F1 and select HSM: Post Utility I get the following error `command 'extension.startHSMPlugin' not found`?

**Comment by george-roberts** [comment]
Hi @dudleyjosh. That's strange, do you have a document open when trying this command? This would usually occur when the plugin has not been loaded.
When a document is open, does the function list / variable list show on the explorer tab?

**Comment by dudleyjosh** [comment]
So I've discovered a couple of things today... mainly that Fusion 360 on Windows is not exactly the same as Fusion 360 on MacOS.

On Windows, I got a similar error dialogue but it asked if I wanted to choose the folder where the *.cps post files were located and then I could use this plugin as expected.

On MacOS the Post dialogue box is completely different (there is no configure button to open the post for edit on the Mac) and the error message for this plugin doesn't ask/allow me to locate the *.cps post files.

**Comment by george-roberts** [comment]
Thanks for the details @dudleyjosh. I'll need to do some investigation into the MacOS version. I'm thinking the node commands used may be windows specific...

You're correct, the post dialog inside of Fusion is different between the two platforms. Currently the properties are displayed a little differently and there are a few features which aren't included in the MAC version (navigating to a folder for example)

**Comment by macmanpb** [comment]
Here the same message: command 'extension.startHSMPlugin' not found
Running on an iMac. Any news fixes for that?

**Comment by george-roberts** [comment]
I updated the extension to support MacOS. Please let me know if you have any issues in the future

**Comment by garciadelcastillo** [comment]
I am still getting this problem for the `Post help` utility:

![image](https://user-images.githubusercontent.com/3866478/209687567-9cf0123c-2494-46fb-887b-0879ede5cf61.png)

I am currently using the plugin version `4.1.0` on VSCode `1.73.1` on Windows.
