### ISSUE TITLE
Fusion 360 Post Processor Utility Disable Auto Line Select will not select false

### ISSUE THREAD

**Issue by drill-bushing** [Autodesk/cam-posteditor#26]
When using Visual code with the Post Processor Utility  unable to select the False option for the Disable Auto Line Select.
This issue is described in detail in Autodesk forum Post Processor Utility for VS Code does not highlight line in post.
Selecting False has no effect. Always revers to True.

**Comment by george-roberts** [comment]
Good afternoon,
I apologize for the delay. Can you try setting this through your user settings by clicking F1 > user settings and then searching for HSMPost Utility. In there, ensure the 'Enable Auto Line Selection' is checked.
If this doesn't work, please can you let me know what version of the add-in and VSCode you are using? Also, what operating system are you on?

**Comment by george-roberts** [comment]
Closing as we received no response and are unable to reproduce
